### PR TITLE
fix: broken link

### PR DESCRIPTION
**Pull request by nicoandmee**
# Changes

* Fix a small typo in `README.md` 🥂

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
ok should not have merged this, the button is gone now fully..

**Comment by nikitavoloboev** [comment]
@nicoandmee can you add it back please

**Comment by nikitavoloboev** [comment]
Ok I reverted the change

**Comment by nicoandmee** [comment]
> Ok I reverted the change

sorry for late reply 😅 - you're absolutely right, my bad. I thought the link was broken 🤦

**Pull request merged**
