### PR TITLE
Add Say-workflow

### PR DESCRIPTION
**Pull request by BaksiLi**
See [say-workflow](https://github.com/BaksiLi/AlfredWorkflows/tree/master/Index/say-workflow).

It is the workflow of my daily use. Highly recommended.

Regards.

### CODE REVIEW

**Comment by nikivdev** [comment]
Whats the difference of your workflow vs?

https://github.com/hzlzh/AlfredWorkflow.com/tree/master/Sources/Workflows/Say-Speak-Text

**Comment by BaksiLi** [comment]
Thanks for your reply.

I didn't know that there was a workflow with similar functionality. I have studied it and this is what I think:

These two workflows have got different niche.

_Say-Speak-Text_ on Alfred 2 does many things (for example selection of voices) which may be useful but requires user to **read the doc before doing things**. It took me a few minutes to get it right for Japanese on my computer. And given the date it was written, **the apple-script part is cracked** as MacOS has changed a lot since then.

My workflow, _Say-workflow_, is written **genuinely for Alfred 3**, with commands that's straight forward: say followed by the language code, and that's done. It is **lightweight and simple**.

Please have a try of both, and you will feel the difference.

Best regards.

**Comment by nikivdev** [comment]
Awesome. I agree, your workflow is simpler and works! 

Thanks for making & sharing it.

**Comment by nikivdev** [comment]
I would change say: trigger to say though. That's the only modification I made myself. The colon seems not necessary.

**Comment by Eldembu** [comment]
> I would change say: trigger to say though. That's the only modification I made myself. The colon seems not necessary.

No problemo, I will make the change later.

**Comment by BaksiLi** [comment]
> I would change say: trigger to say though. That's the only modification I made myself. The colon seems not necessary.

No problemo, I will make the change later.

**Pull request merged**
